# Generated by Django 3.2 on 2022-03-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220319_2330'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['id'], name='users_messa_id_db5f94_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['id'], name='users_profi_id_6c07ac_idx'),
        ),
    ]
